# Generated by Django 6.1.1 on 2026-09-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='multiple_answers', to='exam_engine.questionoption'),
        ),
    ]
