# Generated by Django 6.1.1 on 2026-09-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_engine', '0003_questionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
