# Generated by Django 6.1.1 on 2026-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_engine', '0004_question_correct_answer_question_time_limit_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='question_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
