# Generated by Django 6.1.1 on 2026-10-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_engine', '0005_studentanswer_question_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='teacher_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('TIME_EXPIRED', 'Time Expired'), ('LOCKED', 'Locked'), ('NEEDS_EVALUATION', 'Needs Evaluation'), ('EVALUATED', 'Evaluated')], default='IN_PROGRESS', max_length=20),
        ),
    ]
