# Generated by Django 6.1.1 on 2026-10-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_assessment_access_code_assessment_instructions_and_more'),
        ('accounts', '0002_parentprofile_studentprofile_teacherprofile'),
        ('exam_engine', '0006_studentanswer_teacher_feedback_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentattempt',
            options={'ordering': ['-started_at', '-pk']},
        ),
        migrations.RemoveConstraint(
            model_name='assessmentattempt',
            name='unique_student_assessment_attempt',
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('assessment', 'student'), name='unique_active_student_assessment_attempt'),
        ),
    ]
