# Generated by Django 6.1.1 on 2026-09-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_notice'),
        ('accounts', '0002_parentprofile_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'student_class', 'subject')},
        ),
    ]
