# Generated by Django 6.1.1 on 2026-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='timing_mode',
            field=models.CharField(choices=[('NONE', 'No Time Limit'), ('ENTIRE_TEST', 'Entire Test'), ('PER_QUESTION', 'Per Question')], default='NONE', max_length=20),
        ),
    ]
