# Generated by Django 6.1.1 on 2026-10-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_assessment_duration_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
