# Generated by Django 6.1.1 on 2026-10-03 20:27

import django.db.models.deletion
from django.db import migrations, models


def populate_attendance_status_and_class(apps, schema_editor):
    Attendance = apps.get_model("academics", "Attendance")
    alias = schema_editor.connection.alias
    for record in Attendance.objects.using(alias).select_related("student").iterator():
        Attendance.objects.using(alias).filter(pk=record.pk).update(
            student_class_id=record.student.student_class_id,
            status="PRESENT" if record.is_present else "ABSENT",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_assessment_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='ABSENT', max_length=10),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academics.class'),
        ),
        migrations.RunPython(
            populate_attendance_status_and_class,
            migrations.RunPython.noop,
        ),
    ]
