# Generated by Django 6.1.1 on 2026-10-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_doubtthread_doubtreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='access_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_attempts',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assessment',
            name='passmark_percentage',
            field=models.FloatField(default=40.0),
        ),
        migrations.AddField(
            model_name='assessment',
            name='results_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='show_results_immediately',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='shuffle_questions',
            field=models.BooleanField(default=False),
        ),
    ]
